# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: \.nonprod.yaml$
    key_groups:
    - kms:
      - arn: "arn:aws:kms:us-east-2:<account-id>:alias/enterprise/sops"
        context:
          AccountID: "<nonprod-account-id>"
  - path_regex: \.prod.yaml$
    key_groups:
    - kms:
      - arn: "arn:aws:kms:us-east-2:<account-id>:alias/enterprise/sops"
        context:
          AccountID: "<prod-account-id>"
