resource "aws_quicksight_account_subscription" "this" {
  aws_account_id = data.aws_caller_identity.current.account_id
  region         = data.aws_region.current.region

  account_name          = "${local.account_name}-${local.environment}"
  authentication_method = "IAM_IDENTITY_CENTER"
  edition               = "ENTERPRISE"
  notification_email    = "DL_AWS_ORGANIZATION+${upper(local.account_name)}.${upper(local.environment)}@<your-domain.com>"

  iam_identity_center_instance_arn = one(data.aws_ssoadmin_instances.current.arns)
  admin_pro_group                  = ["AWS PlatformAdmin"]

  lifecycle {
    ignore_changes = [
      account_name,
      notification_email,
    ]
  }
}

resource "aws_quicksight_account_settings" "this" {
  aws_account_id = aws_quicksight_account_subscription.this.aws_account_id
  region         = aws_quicksight_account_subscription.this.region

  termination_protection_enabled = true
}

resource "aws_quicksight_role_membership" "role_groups" {
  for_each = merge([
    for role, groups in local.role_groups : {
      for group in groups : "${role}|${group}" => {
        role  = upper(role)
        group = group
      }
    }
  ]...)

  member_name = each.value.group
  role        = upper(each.value.role)
}

#resource "aws_quicksight_custom_permissions" "adminpro" {
#  custom_permissions_name = "adminpro"
#  capabilities {}
#}

#resource "aws_quicksight_custom_permissions" "authorpro" {
#    custom_permissions_name = "authorpro"
#    capabilities {
  #    self_upgrade_user_role = "DENY"
#    }
#}

resource "aws_quicksight_custom_permissions" "creator" {
  custom_permissions_name = "creator"
  capabilities {
    add_or_run_anomaly_detection_for_analyses        = "DENY"
    analysis                                         = "DENY"
    asana_action                                     = "DENY"
    automate                                         = "DENY"
    bamboo_hr_action                                 = "DENY"
    box_agent_action                                 = "DENY"
    canva_agent_action                               = "DENY"
    comprehend_medical_action                        = "DENY"
    create_and_update_amazon_bedrock_ars_action       = "DENY"
    create_and_update_amazon_bedrock_fs_action        = "DENY"
    create_and_update_amazon_bedrock_krs_action       = "DENY"
    create_and_update_amazon_s_three_action           = "DENY"
    create_and_update_asana_action                    = "DENY"
    create_and_update_bamboo_hr_action                = "DENY"
    create_and_update_box_agent_action                = "DENY"
    create_and_update_canva_agent_action              = "DENY"
    create_and_update_comprehend_action               = "DENY"
    create_and_update_comprehend_medical_action        = "DENY"
    create_and_update_confluence_action               = "DENY"
    create_and_update_dashboard_email_reports         = "DENY"
    create_and_update_data_sources                    = "DENY"
    create_and_update_datasets                        = "DENY"
    create_and_update_fact_set_action                 = "DENY"
    create_and_update_generic_http_action             = "DENY"
    create_and_update_github_action                   = "DENY"
    create_and_update_google_calendar_action          = "DENY"
    create_and_update_hubspot_action                  = "DENY"
    create_and_update_hugging_face_action             = "DENY"
    create_and_update_intercom_action                 = "DENY"
    create_and_update_jira_action                     = "DENY"
    create_and_update_linear_action                   = "DENY"
    create_and_update_mcp_action                      = "DENY"
    create_and_update_monday_action                   = "DENY"
    create_and_update_ms_exchange_action              = "DENY"
    create_and_update_ms_teams_action                 = "DENY"
    create_and_update_new_relic_action                = "DENY"
    create_and_update_notion_action                   = "DENY"
    create_and_update_one_drive_action                = "DENY"
    create_and_update_open_api_action                 = "DENY"
    create_and_update_pager_duty_action               = "DENY"
    create_and_update_salesforce_action               = "DENY"
    create_and_update_sand_p_global_energy_action     = "DENY"
    create_and_update_sand_pgmi_action                = "DENY"
    create_and_update_sap_bill_of_material_action     = "DENY"
    create_and_update_sap_business_partner_action     = "DENY"
    create_and_update_sap_material_stock_action       = "DENY"
    create_and_update_sap_physical_inventory_action    = "DENY"
    create_and_update_sap_product_master_data_action   = "DENY"
    create_and_update_service_now_action              = "DENY"
    create_and_update_share_point_action              = "DENY"
    create_and_update_slack_action                    = "DENY"
    create_and_update_smartsheet_action               = "DENY"
    create_and_update_textract_action                 = "DENY"
    create_and_update_themes                          = "DENY"
    create_and_update_threshold_alerts                = "DENY"
    create_and_update_zendesk_action                  = "DENY"
    create_shared_folders                             = "DENY"
    dashboard                                         = "DENY"
    export_to_csv_in_scheduled_reports                = "DENY"
    export_to_excel_in_scheduled_reports              = "DENY"
    export_to_pdf_in_scheduled_reports                = "DENY"
    fact_set_action                                   = "DENY"
    google_calendar_action                            = "DENY"
    hubspot_action                                    = "DENY"
    include_content_in_scheduled_reports_email        = "DENY"
    intercom_action                                   = "DENY"
    linear_action                                     = "DENY"
    monday_action                                     = "DENY"
    new_relic_action                                  = "DENY"
    notion_action                                     = "DENY"
    pager_duty_action                                 = "DENY"
    publish_without_approval                          = "DENY"
    rename_shared_folders                             = "DENY"
    sand_p_global_energy_action                       = "DENY"
    sand_pgmi_action                                  = "DENY"
    sap_bill_of_material_action                       = "DENY"
    sap_business_partner_action                       = "DENY"
    sap_material_stock_action                         = "DENY"
    sap_physical_inventory_action                     = "DENY"
    sap_product_master_data_action                    = "DENY"
    self_upgrade_user_role                            = "DENY"
    share_amazon_bedrock_ars_action                   = "DENY"
    share_amazon_bedrock_fs_action                    = "DENY"
    share_amazon_bedrock_krs_action                   = "DENY"
    share_amazon_s_three_action                       = "DENY"
    share_analyses                                    = "DENY"
    share_asana_action                                = "DENY"
    share_bamboo_hr_action                            = "DENY"
    share_box_agent_action                            = "DENY"
    share_canva_agent_action                          = "DENY"
    share_comprehend_action                           = "DENY"
    share_comprehend_medical_action                   = "DENY"
    share_confluence_action                           = "DENY"
    share_dashboards                                  = "DENY"
    share_data_sources                                = "DENY"
    share_datasets                                    = "DENY"
    share_fact_set_action                             = "DENY"
    share_generic_http_action                         = "DENY"
    share_github_action                               = "DENY"
    share_google_calendar_action                      = "DENY"
    share_hubspot_action                              = "DENY"
    share_hugging_face_action                         = "DENY"
    share_intercom_action                             = "DENY"
    share_jira_action                                 = "DENY"
    share_linear_action                               = "DENY"
    share_mcp_action                                  = "DENY"
    share_monday_action                               = "DENY"
    share_ms_exchange_action                          = "DENY"
    share_ms_teams_action                             = "DENY"
    share_new_relic_action                            = "DENY"
    share_notion_action                               = "DENY"
    share_one_drive_action                            = "DENY"
    share_open_api_action                             = "DENY"
    share_pager_duty_action                           = "DENY"
    share_salesforce_action                           = "DENY"
    share_sand_p_global_energy_action                 = "DENY"
    share_sand_pgmi_action                            = "DENY"
    share_sap_bill_of_material_action                 = "DENY"
    share_sap_business_partner_action                 = "DENY"
    share_sap_material_stock_action                   = "DENY"
    share_sap_physical_inventory_action               = "DENY"
    share_sap_product_master_data_action              = "DENY"
    share_service_now_action                          = "DENY"
    share_share_point_action                          = "DENY"
    share_slack_action                                = "DENY"
    share_smartsheet_action                           = "DENY"
    share_textract_action                             = "DENY"
    share_zendesk_action                              = "DENY"
    slack_action                                      = "DENY"
    smartsheet_action                                 = "DENY"
    subscribe_dashboard_email_reports                 = "DENY"
    use_asana_action                                  = "DENY"
    use_bamboo_hr_action                              = "DENY"
    use_box_agent_action                              = "DENY"
    use_canva_agent_action                            = "DENY"
    use_comprehend_medical_action                     = "DENY"
    use_fact_set_action                               = "DENY"
    use_google_calendar_action                        = "DENY"
    use_hubspot_action                                = "DENY"
    use_intercom_action                               = "DENY"
    use_linear_action                                 = "DENY"
    use_monday_action                                 = "DENY"
    use_new_relic_action                              = "DENY"
    use_notion_action                                 = "DENY"
    use_pager_duty_action                             = "DENY"
    use_sand_p_global_energy_action                   = "DENY"
    use_sand_pgmi_action                              = "DENY"
    use_sap_bill_of_material_action                   = "DENY"
    use_sap_business_partner_action                   = "DENY"
    use_sap_material_stock_action                     = "DENY"
    use_sap_physical_inventory_action                 = "DENY"
    use_sap_product_master_data_action                = "DENY"
    use_slack_action                                  = "DENY"
    use_smartsheet_action                             = "DENY"
    use_zendesk_action                                = "DENY"
    view_account_spice_capacity                       = "DENY"
    zendesk_action                                    = "DENY"
  }
}

resource "aws_quicksight_custom_permissions" "general" {
  custom_permissions_name = "general"
  capabilities {
    add_or_run_anomaly_detection_for_analyses        = "DENY"
    analysis                                         = "DENY"
    asana_action                                     = "DENY"
    automate                                         = "DENY"
    bamboo_hr_action                                 = "DENY"
    box_agent_action                                 = "DENY"
    canva_agent_action                               = "DENY"
    comprehend_medical_action                        = "DENY"
    create_and_update_amazon_bedrock_ars_action       = "DENY"
    create_and_update_amazon_bedrock_fs_action        = "DENY"
    create_and_update_amazon_bedrock_krs_action       = "DENY"
    create_and_update_amazon_s_three_action           = "DENY"
    create_and_update_asana_action                    = "DENY"
    create_and_update_bamboo_hr_action                = "DENY"
    create_and_update_box_agent_action                = "DENY"
    create_and_update_canva_agent_action              = "DENY"
    create_and_update_comprehend_action               = "DENY"
    create_and_update_comprehend_medical_action        = "DENY"
    create_and_update_confluence_action               = "DENY"
    create_and_update_dashboard_email_reports         = "DENY"
    create_and_update_data_sources                    = "DENY"
    create_and_update_datasets                        = "DENY"
    create_and_update_fact_set_action                 = "DENY"
    create_and_update_generic_http_action             = "DENY"
    create_and_update_github_action                   = "DENY"
    create_and_update_google_calendar_action          = "DENY"
    create_and_update_hubspot_action                  = "DENY"
    create_and_update_hugging_face_action             = "DENY"
    create_and_update_intercom_action                 = "DENY"
    create_and_update_jira_action                     = "DENY"
    create_and_update_linear_action                   = "DENY"
    create_and_update_mcp_action                      = "DENY"
    create_and_update_monday_action                   = "DENY"
    create_and_update_ms_exchange_action              = "DENY"
    create_and_update_ms_teams_action                 = "DENY"
    create_and_update_new_relic_action                = "DENY"
    create_and_update_notion_action                   = "DENY"
    create_and_update_one_drive_action                = "DENY"
    create_and_update_open_api_action                 = "DENY"
    create_and_update_pager_duty_action               = "DENY"
    create_and_update_salesforce_action               = "DENY"
    create_and_update_sand_p_global_energy_action      = "DENY"
    create_and_update_sand_pgmi_action                = "DENY"
    create_and_update_sap_bill_of_material_action     = "DENY"
    create_and_update_sap_business_partner_action     = "DENY"
    create_and_update_sap_material_stock_action       = "DENY"
    create_and_update_sap_physical_inventory_action    = "DENY"
    create_and_update_sap_product_master_data_action   = "DENY"
    create_and_update_service_now_action              = "DENY"
    create_and_update_share_point_action              = "DENY"
    create_and_update_slack_action                    = "DENY"
    create_and_update_smartsheet_action               = "DENY"
    create_and_update_textract_action                 = "DENY"
    create_and_update_themes                          = "DENY"
    create_and_update_threshold_alerts                = "DENY"
    create_and_update_zendesk_action                  = "DENY"
    create_chat_agents                                = "DENY"
    create_shared_folders                             = "DENY"
    dashboard                                         = "DENY"
    export_to_csv_in_scheduled_reports                = "DENY"
    export_to_excel_in_scheduled_reports              = "DENY"
    export_to_pdf_in_scheduled_reports                = "DENY"
    fact_set_action                                   = "DENY"
    google_calendar_action                            = "DENY"
    hubspot_action                                    = "DENY"
    include_content_in_scheduled_reports_email        = "DENY"
    intercom_action                                   = "DENY"
    linear_action                                     = "DENY"
    monday_action                                     = "DENY"
    new_relic_action                                  = "DENY"
    notion_action                                     = "DENY"
    pager_duty_action                                 = "DENY"
    publish_without_approval                          = "DENY"
    rename_shared_folders                             = "DENY"
    research                                          = "DENY"
    sand_p_global_energy_action                       = "DENY"
    sand_pgmi_action                                  = "DENY"
    sap_bill_of_material_action                       = "DENY"
    sap_business_partner_action                       = "DENY"
    sap_material_stock_action                         = "DENY"
    sap_physical_inventory_action                     = "DENY"
    sap_product_master_data_action                    = "DENY"
    self_upgrade_user_role                            = "DENY"
    share_amazon_bedrock_ars_action                   = "DENY"
    share_amazon_bedrock_fs_action                    = "DENY"
    share_amazon_bedrock_krs_action                   = "DENY"
    share_amazon_s_three_action                       = "DENY"
    share_analyses                                    = "DENY"
    share_asana_action                                = "DENY"
    share_bamboo_hr_action                            = "DENY"
    share_box_agent_action                            = "DENY"
    share_canva_agent_action                          = "DENY"
    share_comprehend_action                           = "DENY"
    share_comprehend_medical_action                   = "DENY"
    share_confluence_action                           = "DENY"
    share_dashboards                                  = "DENY"
    share_data_sources                                = "DENY"
    share_datasets                                    = "DENY"
    share_fact_set_action                             = "DENY"
    share_generic_http_action                         = "DENY"
    share_github_action                               = "DENY"
    share_google_calendar_action                      = "DENY"
    share_hubspot_action                              = "DENY"
    share_hugging_face_action                         = "DENY"
    share_intercom_action                             = "DENY"
    share_jira_action                                 = "DENY"
    share_linear_action                               = "DENY"
    share_mcp_action                                  = "DENY"
    share_monday_action                               = "DENY"
    share_ms_exchange_action                          = "DENY"
    share_ms_teams_action                             = "DENY"
    share_new_relic_action                            = "DENY"
    share_notion_action                               = "DENY"
    share_one_drive_action                            = "DENY"
    share_open_api_action                             = "DENY"
    share_pager_duty_action                           = "DENY"
    share_salesforce_action                           = "DENY"
    share_sand_p_global_energy_action                 = "DENY"
    share_sand_pgmi_action                            = "DENY"
    share_sap_bill_of_material_action                 = "DENY"
    share_sap_business_partner_action                 = "DENY"
    share_sap_material_stock_action                   = "DENY"
    share_sap_physical_inventory_action               = "DENY"
    share_sap_product_master_data_action              = "DENY"
    share_service_now_action                          = "DENY"
    share_share_point_action                          = "DENY"
    share_slack_action                                = "DENY"
    share_smartsheet_action                           = "DENY"
    share_textract_action                             = "DENY"
    share_zendesk_action                              = "DENY"
    slack_action                                      = "DENY"
    smartsheet_action                                 = "DENY"
    subscribe_dashboard_email_reports                 = "DENY"
    use_asana_action                                  = "DENY"
    use_bamboo_hr_action                              = "DENY"
    use_box_agent_action                              = "DENY"
    use_canva_agent_action                            = "DENY"
    use_comprehend_medical_action                     = "DENY"
    use_fact_set_action                               = "DENY"
    use_google_calendar_action                        = "DENY"
    use_hubspot_action                                = "DENY"
    use_intercom_action                               = "DENY"
    use_linear_action                                 = "DENY"
    use_monday_action                                 = "DENY"
    use_new_relic_action                              = "DENY"
    use_notion_action                                 = "DENY"
    use_pager_duty_action                             = "DENY"
    use_sand_p_global_energy_action                   = "DENY"
    use_sand_pgmi_action                              = "DENY"
    use_sap_bill_of_material_action                   = "DENY"
    use_sap_business_partner_action                   = "DENY"
    use_sap_material_stock_action                     = "DENY"
    use_sap_physical_inventory_action                 = "DENY"
    use_sap_product_master_data_action                = "DENY"
    use_slack_action                                  = "DENY"
    use_smartsheet_action                             = "DENY"
    use_zendesk_action                                = "DENY"
    view_account_spice_capacity                       = "DENY"
    zendesk_action                                    = "DENY"
  }
}


# Need to loop through users so this profile doesn't affect authorpro group, use
# this block when mapping to idc groups is supported

# resource "aws_quicksight_role_custom_permission" "author_pro" {
#  role                    = "AUTHOR_PRO"
#  custom_permissions_name = aws_quicksight_custom_permissions.creator.custom_permissions_name
# }

resource "aws_quicksight_user_custom_permission" "creator" {
  for_each               = data.aws_identitystore_user.creator_idc_user
  user_name              = each.value.user_name
  custom_permissions_name = aws_quicksight_custom_permissions.creator.custom_permissions_name
}

resource "aws_quicksight_role_custom_permission" "reader_pro" {
  role                    = "READER_PRO"
  custom_permissions_name = aws_quicksight_custom_permissions.general.custom_permissions_name
}
